#!/bin/bash

if [ $# -eq 0 ]; then
       KEY_PATH=.
else
       KEY_PATH=$1
fi

if [ ! -e debian/gooroom-uefi-ca.der ]; then
  openssl req -new -x509 -newkey rsa:2048 \
            -subj "/CN=Gooroom VENDOR CERT/" \
            -keyout $KEY_PATH/gooroom.key \
            -out $KEY_PATH/gooroom.crt -days 3650 \
            -nodes -sha256

  openssl x509 -in $KEY_PATH/gooroom.crt -out $KEY_PATH/gooroom-uefi-ca.der -outform DER
fi

cp $KEY_PATH/gooroom-uefi-ca.der debian/gooroom-uefi-ca.der
