#!/bin/bash

#
# Copyright (C) 2019-2020 jongkyung.woo <jongkyung.woo@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#

ca_file=gooroom-uefi-ca.der

openssl req -new -x509 -newkey rsa:2048 \
            -subj "/CN=Gooroom Secure Boot CA/DC=www.gooroom.kr/L=Yeongdeungpo-gu/ST=Seoul/C=KR/O=Gooroom Platform Forum/OU=Gooroom Bootloader Team/" \
            -keyout gooroom.key \
            -out gooroom.crt -days 3650 \
            -nodes -sha256

openssl x509 -in gooroom.crt -out ${ca_file} -outform DER
